export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const ADJUST_QTY = "ADJUST_QTY";
export const LOAD_CURRENT_ITEM = "LOAD_CURRENT_ITEM";
export const CHANGE_ITEM_COLOR = "CHANGE_ITEM_COLOR";
export const CHANGE_ITEM_SIZE = "CHANGE_ITEM_SIZE";